### ISSUE TITLE
Getting Deprecation Warning while running the project

### ISSUE THREAD

**Issue by HaroldObasi** [vasyas/charger-simulator#9]
I am running a python websocket server with ocpp, its running on port 9000

i followed the installation docs for this project but when i run the project with yarn start ws:://0.0.0.0:9000/, i get this : 

`[info] Starting charger simulator {
  csURL: 'ws:://0.0.0.0:9000/',
  connectorId: 1,
  chargerId: 'test',
  idTag: '12345678'
}`

`
Charger simulator starting 
(node:73090) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use node --trace-deprecation ... to show where the warning was created)
`

not sure if it's my server, or if maybe it is from the deprecation warning

**Comment by vasyas** [comment]
Hey @HaroldObasi !

This warning is caused by using classic Yarn in NodeJS 21+

To fix, downgrade NodeJS to the previous version or wait until they release a fix for Yarn, as described in https://github.com/yarnpkg/yarn/issues/9005.

It's also should be safe to just ignore this warning.
